---
title: "Class 545a Notes"
author: "Adrian jones"
date: "September 22, 2015"
output: html_document
---

##Today we seem to be doign stuff in ggplot2

We have homework due, thoughts about workflow, if document will be mostly code, do and R script and used the spiral bound book thing.  If the document is more chatty with a bit of code use markdown from the start.

## Slides and things
[Slides and the class](https://stat545-ubc.github.io/cm005_still-data-ggplot2-rmarkdown.html) 

ggplot2 is the current package, ggplot is an old attempt.
All about
* Facilitate comparisons 
* Identify trends

ggplot2:  use facetting to put stuff in small subplots by some category.
aes stands for asthetic mapping?
add smooth stuff with geom_smooth
allsorts of ways that ggplot makes things smoother

Wrangle your data to make things easier generally speaking.  When people have a hard time with graphics, it is often because of trouble with data wrangling.
* use data.frame
* use factors
* be boss of factors
* keep data tidy
* be happy to reshape data.

factors can be moved around using `reorder()`
####RStudio has cheetsheets under the help thing


## ggplot2 tutorial work

```{r}
library(gapminder)
library(ggplot2)

str(gapminder)

#this initialises the gapminder plot, we just add options with +
p <- ggplot(gapminder, aes(x = gdpPercap, y = lifeExp))


p + geom_point()

#really we'd like that to be a log
p + geom_point() + scale_x_log10()

#Now we like the log10 thingy, so keep that as part of the plot for the future, leaving other stuff as still manipulable.

p <- p + scale_x_log10()

#We tell ggplot2 that we want an aesthetic of colour linked to the continents.

p + geom_point(aes(colour = continent))

```

